name: Development build

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      name: ${{ steps.details.outputs.name }}
      version: ${{ steps.details.outputs.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract project details
        id: details
        shell: bash
        run: |
          echo "name=$(grep 'rootProject.name' settings.gradle.kts | awk -F "=" '{print $2}' | tr -d ' \"\n')" >> $GITHUB_OUTPUT
          branch_name="${GITHUB_REF_NAME//\//-}"
          echo "version=${branch_name}-${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

  build:
    needs: prepare
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build project
        uses: ./.github/actions/gradle-build
        with:
          gradle-command: ./gradlew --no-daemon test :velocity:shadowJar :bungeecord:shadowJar

      - name: Create output directory
        shell: bash
        run: mkdir output

      - name: Move jars
        shell: bash
        run: |
          mv velocity/build/libs/*.jar output/${{ needs.prepare.outputs.name }}-Velocity-${{ needs.prepare.outputs.version }}.jar
          mv bungeecord/build/libs/*.jar output/${{ needs.prepare.outputs.name }}-BungeeCord-${{ needs.prepare.outputs.version }}.jar

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ needs.prepare.outputs.name }}
          path: output/
